#!/usr/bin/env python3
# Generated by tools/build_login_script.py; edit the source modules instead.
"""Interactive WPS login bootstrap using a local Chrome session.

The adapter cannot read cookies from a normal web page: WPS is a different
origin and the important session cookies are HttpOnly.  This module uses the
Chrome DevTools Protocol only with a temporary, isolated browser profile.  A
person completes the login in the official WPS page, then the helper reads
the cookies Chrome itself has stored and sends the minimum useful snapshot to
the adapter host over HTTP or HTTPS.  Remote HTTP requires explicit opt-in.
SSH and local-file targets remain available as fallbacks.

No WPS password is handled by this process and no cookie value is printed.
The server-side adapter continues to use its existing ``rtk`` refresh flow
after this one-time bootstrap.
"""

from __future__ import annotations

import base64
import ipaddress
import json
import os
import posixpath
import re
import secrets
import shlex
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from http.client import HTTPConnection, HTTPSConnection
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode, urlsplit, urlunsplit
from urllib.request import ProxyHandler, Request, build_opener

from dataclasses import field

@dataclass(frozen=True, slots=True)
class WpsCredentials:
    """A point-in-time credential snapshot for the standalone helper."""

    cookie: str = field(default="", repr=False)
    csrf_token: str = field(default="", repr=False)



DEFAULT_LOGIN_URL = "https://365.kdocs.cn/space/"
DEFAULT_COOKIE_DOMAIN_SUFFIX = "kdocs.cn"
DEFAULT_REMOTE_COOKIE_PATH = "/etc/wps-adapter/secrets/wps-cookie"
DEFAULT_REMOTE_CSRF_PATH = "/etc/wps-adapter/secrets/wps-csrf"
DEFAULT_REMOTE_WORKSPACE_PATH = "/etc/wps-adapter/secrets/wps-workspace.json"
REMOTE_SECRET_DIR = "/etc/wps-adapter/secrets"
MAX_COOKIE_SNAPSHOT_BYTES = 4 * 1024 * 1024
MAX_ADAPTER_RESPONSE_BYTES = 1 * 1024 * 1024


class LoginError(RuntimeError):
    """A safe, user-facing error from the interactive login helper."""


@dataclass(frozen=True, slots=True)
class WpsWorkspaceSelection:
    """Workspace IDs read from the current official WPS page URL."""

    tenant_id: str
    group_id: str
    root_id: str
    spaces: tuple["WpsWorkspaceCandidate", ...] = ()


@dataclass(frozen=True, slots=True)
class WpsWorkspaceCandidate:
    """A workspace returned by the optional account space discovery API."""

    tenant_id: str
    group_id: str
    name: str


_WORKSPACE_ID_PATTERN = re.compile(r"^[A-Za-z0-9._-]{1,256}$")
_SPACE_PATH_PATTERN = re.compile(
    r"^/space/([^/]+)/([^/]+)(?:/([^/]+))?/?$",
    re.IGNORECASE,
)


def _workspace_id(value: str, *, field_name: str) -> str:
    if not _WORKSPACE_ID_PATTERN.fullmatch(value):
        raise LoginError(f"WPS {field_name} 格式不正确")
    return value


def _workspace_payload(selection: WpsWorkspaceSelection) -> dict[str, object]:
    if not isinstance(selection, WpsWorkspaceSelection):
        raise LoginError("WPS 工作区信息无效")
    payload: dict[str, object] = {
        "group_id": _workspace_id(selection.group_id, field_name="群组 ID"),
        "root_id": _workspace_id(selection.root_id, field_name="目录 ID"),
    }
    if selection.spaces:
        payload["spaces"] = [
            {
                "group_id": _workspace_id(item.group_id, field_name="群组 ID"),
                "root_id": "0",
                "name": item.name,
            }
            for item in selection.spaces
        ]
    return payload


def _workspace_parts_from_page_url(
    url: str,
) -> tuple[str, str, str | None] | None:
    """Parse the workspace context and optional folder from a WPS URL."""

    _host_from_url(url)
    match = _SPACE_PATH_PATTERN.fullmatch(urlsplit(url).path)
    if match is None:
        return None
    tenant_id = _workspace_id(match.group(1), field_name="企业 ID")
    group_id = _workspace_id(match.group(2), field_name="群组 ID")
    folder_id = match.group(3)
    return (
        tenant_id,
        group_id,
        None if folder_id is None else _workspace_id(folder_id, field_name="目录 ID"),
    )


def workspace_from_page_url(url: str) -> WpsWorkspaceSelection | None:
    """Extract a concrete folder selection from an observed WPS space URL."""

    parts = _workspace_parts_from_page_url(url)
    if parts is None or parts[2] is None:
        return None
    tenant_id, group_id, folder_id = parts
    assert folder_id is not None
    return WpsWorkspaceSelection(
        tenant_id=tenant_id,
        group_id=group_id,
        root_id=folder_id,
    )


def workspace_root_from_page_url(url: str) -> WpsWorkspaceSelection | None:
    """Extract the enterprise/group context and select the WPS root directory.

    WPS may restore the last folder in the URL after login. That folder is a
    browser navigation detail, not an appropriate default for the adapter, so
    both the group URL and a group URL with an optional folder map to
    ``root_id=0`` here.
    """

    parts = _workspace_parts_from_page_url(url)
    if parts is None:
        return None
    tenant_id, group_id, _folder_id = parts
    return WpsWorkspaceSelection(
        tenant_id=tenant_id,
        group_id=group_id,
        root_id="0",
    )


def _host_from_url(url: str) -> str:
    parts = urlsplit(url)
    try:
        port = parts.port
    except ValueError as exc:
        raise LoginError("登录地址中的端口无效") from exc
    host = parts.hostname.rstrip(".").casefold() if parts.hostname else ""
    if (
        parts.scheme != "https"
        or not host
        or parts.username
        or parts.password
        or port not in {None, 443}
        or not (host == "kdocs.cn" or host.endswith(".kdocs.cn"))
    ):
        raise LoginError("登录地址必须是不带账号信息的 HTTPS WPS 地址")
    return host


def _domain_without_dot(value: str) -> str:
    return value.strip().lstrip(".").rstrip(".").casefold()


def _domain_matches_host(domain: str, host: str) -> bool:
    normalized = _domain_without_dot(domain)
    return bool(normalized) and (host == normalized or host.endswith("." + normalized))


def _domain_is_allowed(domain: str, suffix: str) -> bool:
    normalized = _domain_without_dot(domain)
    allowed = _domain_without_dot(suffix)
    return bool(normalized and allowed) and (
        normalized == allowed or normalized.endswith("." + allowed)
    )


def _cookie_rank(cookie: Mapping[str, object], host: str) -> tuple[int, int, int]:
    domain = _domain_without_dot(str(cookie.get("domain", "")))
    path = str(cookie.get("path", "/"))
    # Prefer a cookie set for the exact drive host, then the more specific
    # domain/path.  Chrome can contain same-name cookies at multiple scopes.
    return (1 if domain == host else 0, len(domain), len(path))


def _safe_cookie_part(value: str, *, name: bool = False) -> bool:
    if (
        not value
        or len(value) > 64 * 1024
        or any(ord(char) < 0x20 or ord(char) == 0x7F for char in value)
    ):
        return False
    if ";" in value:
        return False
    if name and any(char in value for char in "()<>@,;:\\\"/[]?={} \t"):
        return False
    return True


def _select_cookies(
    cookies: Sequence[Mapping[str, object]],
    *,
    host: str,
    domain_suffix: str,
) -> list[Mapping[str, object]]:
    selected: dict[str, Mapping[str, object]] = {}
    for cookie in cookies:
        if not isinstance(cookie, Mapping):
            continue
        domain = str(cookie.get("domain", ""))
        if not _domain_matches_host(domain, host):
            continue
        if not _domain_is_allowed(domain, domain_suffix):
            continue
        name = str(cookie.get("name", ""))
        value = str(cookie.get("value", ""))
        if not _safe_cookie_part(name, name=True) or not _safe_cookie_part(value):
            continue
        key = name.casefold()
        previous = selected.get(key)
        if previous is None or _cookie_rank(cookie, host) > _cookie_rank(previous, host):
            selected[key] = cookie
    return sorted(selected.values(), key=lambda item: str(item.get("name", "")).casefold())


def credentials_from_cookies(
    cookies: Sequence[Mapping[str, object]],
    *,
    base_url: str = DEFAULT_LOGIN_URL,
    domain_suffix: str = DEFAULT_COOKIE_DOMAIN_SUFFIX,
    require_refresh_cookie: bool = True,
) -> tuple[WpsCredentials, tuple[str, ...]]:
    """Build the adapter credential snapshot from Chrome cookie objects.

    Cookies are limited to the configured WPS domain suffix and cookies that
    Chrome says match the drive host.  ``rtk`` is retained even though its
    browser path is ``/passport/secure`` because the adapter sends the same
    stored snapshot to the confirmed account refresh endpoint.
    """

    host = _host_from_url(base_url)
    selected = _select_cookies(cookies, host=host, domain_suffix=domain_suffix)
    if not selected:
        raise LoginError("没有找到属于 WPS 云盘的登录 Cookie，请确认已经登录")

    pairs = [
        f"{cookie['name']}={cookie.get('value', '')}"
        for cookie in selected
    ]
    by_name = {
        str(cookie.get("name", "")).casefold(): str(cookie.get("value", ""))
        for cookie in selected
    }
    csrf = by_name.get("csrf", "")
    if not csrf:
        raise LoginError("登录 Cookie 中没有 csrf，请在 WPS 页面完成登录后重试")
    if require_refresh_cookie and not by_name.get("rtk"):
        raise LoginError(
            "登录 Cookie 中没有 rtk，无法启用自动续期；请使用此助手重新登录 WPS 后重试"
        )
    cookie_header = "; ".join(pairs)
    if len(cookie_header) > MAX_COOKIE_SNAPSHOT_BYTES:
        raise LoginError("WPS Cookie 快照过大")
    return WpsCredentials(cookie=cookie_header, csrf_token=csrf), tuple(
        str(cookie.get("name", "")) for cookie in selected
    )


def _cookie_value(cookies: Sequence[Mapping[str, object]], name: str) -> str:
    """Return a small non-secret routing cookie used for account context."""

    for cookie in cookies:
        if str(cookie.get("name", "")).casefold() == name.casefold():
            value = cookie.get("value")
            if isinstance(value, str) and value:
                return value
    return ""


def _atomic_write(path: str | Path, value: str) -> None:
    target = Path(path)
    if not target.is_absolute():
        raise LoginError("凭据文件路径必须是绝对路径")
    if "\x00" in str(target) or "\n" in str(target) or "\r" in str(target):
        raise LoginError("凭据文件路径无效")
    target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    try:
        os.chmod(target.parent, 0o700)
    except OSError as exc:
        raise LoginError("无法保护凭据目录") from exc
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{target.name}.",
        dir=str(target.parent),
        text=True,
    )
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            descriptor = -1
            stream.write(value)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
    finally:
        if descriptor != -1:
            os.close(descriptor)
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def write_local_credentials(
    credentials: WpsCredentials,
    *,
    output_dir: str | Path,
) -> tuple[Path, Path]:
    """Write a local credential pair without putting values on argv."""

    directory = Path(output_dir)
    if not directory.is_absolute():
        raise LoginError("本地凭据目录必须是绝对路径")
    cookie_path = directory / "wps-cookie"
    csrf_path = directory / "wps-csrf"
    _atomic_write(cookie_path, credentials.cookie)
    _atomic_write(csrf_path, credentials.csrf_token)
    return cookie_path, csrf_path


def write_local_workspace(
    workspace: WpsWorkspaceSelection,
    *,
    output_dir: str | Path,
) -> Path:
    """Write the selected WPS workspace next to local credentials."""

    directory = Path(output_dir)
    if not directory.is_absolute():
        raise LoginError("本地凭据目录必须是绝对路径")
    workspace_path = directory / "wps-workspace.json"
    _atomic_write(
        workspace_path,
        json.dumps(_workspace_payload(workspace), ensure_ascii=True, separators=(",", ":")),
    )
    return workspace_path


_REMOTE_WRITE_SCRIPT = r'''import json, os, stat, sys, tempfile

SECRET_DIR = "/etc/wps-adapter/secrets"

def validate_secret_path(path):
    if not isinstance(path, str) or not path.startswith(SECRET_DIR + "/"):
        raise ValueError("credential path must be inside the adapter secret directory")
    relative = path[len(SECRET_DIR) + 1:]
    if not relative or "/" in relative or relative in {".", ".."}:
        raise ValueError("credential path must be a direct secret file")
    if not all("A" <= char <= "Z" or "a" <= char <= "z" or "0" <= char <= "9" or char in "._-" for char in relative):
        raise ValueError("credential path contains an invalid file name")
    if os.path.normpath(path) != path or os.path.realpath(SECRET_DIR) != SECRET_DIR:
        raise ValueError("credential path must not use symlinks or traversal")
    try:
        directory_stat = os.lstat(SECRET_DIR)
    except FileNotFoundError as exc:
        raise ValueError("adapter secret directory does not exist") from exc
    if not stat.S_ISDIR(directory_stat.st_mode):
        raise ValueError("adapter secret path is not a directory")
    return path

def validate_workspace_id(value):
    if not isinstance(value, str) or not value or len(value) > 256:
        raise ValueError("invalid workspace identifier")
    if not all("A" <= char <= "Z" or "a" <= char <= "z" or "0" <= char <= "9" or char in ".-_" for char in value):
        raise ValueError("invalid workspace identifier")
    return value

def atomic_write(path, value):
    target = validate_secret_path(path)
    directory = SECRET_DIR
    os.chmod(directory, 0o700)
    previous_stat = None
    try:
        previous_stat = os.lstat(target)
        if stat.S_ISLNK(previous_stat.st_mode) or not stat.S_ISREG(previous_stat.st_mode):
            raise ValueError("credential target must be a regular file")
    except FileNotFoundError:
        pass
    fd, temporary = tempfile.mkstemp(prefix="." + os.path.basename(target) + ".", dir=directory, text=True)
    try:
        os.fchmod(fd, 0o600)
        if previous_stat is not None and hasattr(os, "fchown"):
            os.fchown(fd, previous_stat.st_uid, previous_stat.st_gid)
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            fd = -1
            stream.write(value)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
    finally:
        if fd != -1:
            os.close(fd)
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass

raw_payload = sys.stdin.buffer.read(8 * 1024 * 1024 + 1)
if len(raw_payload) > 8 * 1024 * 1024:
    raise ValueError("credential payload is too large")
data = json.loads(raw_payload.decode("utf-8"))
cookie_path = data["cookie_path"]
csrf_path = data["csrf_path"]
cookie = data["cookie"]
csrf = data["csrf"]
if not all(isinstance(item, str) and item for item in (cookie_path, csrf_path, cookie, csrf)):
    raise ValueError("invalid credential payload")
cookie_path = validate_secret_path(cookie_path)
csrf_path = validate_secret_path(csrf_path)
if cookie_path == csrf_path:
    raise ValueError("credential paths must be different")
if any(any(ord(char) < 0x20 or ord(char) == 0x7f for char in item) for item in (cookie, csrf)):
    raise ValueError("invalid credential value")
atomic_write(cookie_path, cookie)
atomic_write(csrf_path, csrf)
workspace_path = data.get("workspace_path")
workspace = data.get("workspace")
if workspace_path is not None or workspace is not None:
    workspace_path = validate_secret_path(workspace_path)
    if not isinstance(workspace, dict):
        raise ValueError("invalid workspace payload")
    group_id = validate_workspace_id(workspace.get("group_id"))
    root_id = validate_workspace_id(workspace.get("root_id"))
    atomic_write(
        workspace_path,
        json.dumps({"group_id": group_id, "root_id": root_id}, ensure_ascii=True, separators=(",", ":")),
    )
print("credentials-updated")
'''


def _validate_remote_secret_path(path: str, *, label: str) -> None:
    if not isinstance(path, str) or not path.startswith(REMOTE_SECRET_DIR + "/"):
        raise LoginError(f"远程{label}路径必须位于 /etc/wps-adapter/secrets 目录")
    relative = path[len(REMOTE_SECRET_DIR) + 1:]
    if (
        not relative
        or "/" in relative
        or relative in {".", ".."}
        or any(
            not ("A" <= char <= "Z" or "a" <= char <= "z" or "0" <= char <= "9" or char in "._-")
            for char in relative
        )
        or posixpath.normpath(path) != path
    ):
        raise LoginError(f"远程{label}路径必须是 secret 目录下的普通文件名")


def push_credentials_over_ssh(
    credentials: WpsCredentials,
    *,
    ssh_target: str,
    cookie_path: str = DEFAULT_REMOTE_COOKIE_PATH,
    csrf_path: str = DEFAULT_REMOTE_CSRF_PATH,
    workspace: WpsWorkspaceSelection | None = None,
    workspace_path: str = DEFAULT_REMOTE_WORKSPACE_PATH,
    identity_file: str | None = None,
    port: int = 22,
    password_auth: bool = False,
    timeout: float = 30.0,
) -> None:
    """Atomically replace the remote secret files through an SSH stdin pipe."""

    if not ssh_target or any(char in ssh_target for char in "\r\n\x00"):
        raise LoginError("SSH 目标不能为空且不能包含换行")
    if any(char.isspace() for char in ssh_target):
        raise LoginError("SSH 目标不能包含空格")
    if not 1 <= port <= 65535:
        raise LoginError("SSH 端口必须在 1 到 65535 之间")
    if timeout <= 0:
        raise LoginError("SSH 超时时间必须为正数")
    _validate_remote_secret_path(cookie_path, label="凭据")
    _validate_remote_secret_path(csrf_path, label="凭据")
    if workspace is not None:
        _validate_remote_secret_path(workspace_path, label="工作区")
        workspace_data = _workspace_payload(workspace)
    else:
        workspace_data = None
    if cookie_path == csrf_path:
        raise LoginError("远程 Cookie 和 CSRF 路径必须不同")
    if workspace is not None and workspace_path in {cookie_path, csrf_path}:
        raise LoginError("远程工作区和凭据路径不能重复")

    payload_data: dict[str, object] = {
        "cookie_path": cookie_path,
        "csrf_path": csrf_path,
        "cookie": credentials.cookie,
        "csrf": credentials.csrf_token,
    }
    if workspace_data is not None:
        payload_data["workspace_path"] = workspace_path
        payload_data["workspace"] = workspace_data
    payload = json.dumps(payload_data, ensure_ascii=True, separators=(",", ":")).encode("utf-8")
    remote_command = (
        "python3 -c "
        + shlex.quote(_REMOTE_WRITE_SCRIPT)
    )
    command = ["ssh", "-F", "/dev/null"]
    if identity_file:
        command.extend(["-i", os.path.expanduser(identity_file)])
    if password_auth:
        command.extend(
            [
                "-o",
                "PubkeyAuthentication=no",
                "-o",
                "PreferredAuthentications=password,keyboard-interactive",
            ]
        )
    if port != 22:
        command.extend(["-p", str(port)])
    command.extend(["--", ssh_target, remote_command])
    try:
        completed = subprocess.run(
            command,
            input=payload,
            stdout=subprocess.PIPE,
            stderr=None if password_auth else subprocess.PIPE,
            timeout=timeout,
            check=False,
        )
    except FileNotFoundError as exc:
        raise LoginError("本机没有 ssh 命令") from exc
    except subprocess.TimeoutExpired as exc:
        raise LoginError("SSH 同步凭据超时") from exc
    if completed.returncode != 0:
        raise LoginError(
            "SSH 同步凭据失败；请确认主机、端口、用户名和登录方式后重试"
        )


def _is_loopback_host(host: str) -> bool:
    normalized = host.strip("[]").casefold()
    if normalized == "localhost":
        return True
    try:
        return ipaddress.ip_address(normalized).is_loopback
    except ValueError:
        return False


def _adapter_url_parts(
    adapter_url: str,
    *,
    allow_insecure_http: bool = False,
) -> tuple[str, str, int | None]:
    if not isinstance(adapter_url, str) or not adapter_url:
        raise LoginError("适配器地址不能为空")
    if any(ord(char) < 0x20 or ord(char) == 0x7F for char in adapter_url):
        raise LoginError("适配器地址不能包含控制字符")
    parts = urlsplit(adapter_url)
    try:
        port = parts.port
    except ValueError as exc:
        raise LoginError("适配器地址中的端口无效") from exc
    host = parts.hostname
    if (
        parts.scheme not in {"https", "http"}
        or not host
        or parts.username
        or parts.password
        or parts.query
        or parts.fragment
        or parts.path not in {"", "/"}
    ):
        raise LoginError("适配器地址应为不带路径、账号或查询参数的 HTTP 或 HTTPS 地址")
    if (
        parts.scheme == "http"
        and not _is_loopback_host(host)
        and not allow_insecure_http
    ):
        raise LoginError("远程 HTTP 会明文传输凭据；确认后请使用 --allow-http")
    return parts.scheme, host, port


def is_remote_http_url(adapter_url: str) -> bool:
    """Return whether an adapter URL sends credentials over remote HTTP."""

    scheme, host, _ = _adapter_url_parts(adapter_url, allow_insecure_http=True)
    return scheme == "http" and not _is_loopback_host(host)


def _validate_adapter_auth(username: str, password: str) -> None:
    if not isinstance(username, str) or not username or ":" in username:
        raise LoginError("适配器用户名不能为空且不能包含冒号")
    if not isinstance(password, str) or not password:
        raise LoginError("适配器密码不能为空")
    if any(ord(char) < 0x20 or ord(char) == 0x7F for char in username + password):
        raise LoginError("适配器账号或密码不能包含控制字符")


def _cookie_payload(cookies: Sequence[Mapping[str, object]]) -> list[dict[str, str]]:
    payload: list[dict[str, str]] = []
    for raw_cookie in cookies:
        if not isinstance(raw_cookie, Mapping):
            continue
        name = raw_cookie.get("name")
        value = raw_cookie.get("value")
        if not isinstance(name, str) or not isinstance(value, str):
            continue
        item = {"name": name, "value": value}
        for field_name in ("domain", "path"):
            field_value = raw_cookie.get(field_name)
            if isinstance(field_value, str):
                item[field_name] = field_value
        payload.append(item)
    if not payload:
        raise LoginError("没有可同步的 WPS Cookie")
    if len(payload) > 256:
        raise LoginError("WPS Cookie 数量异常")
    return payload


def _read_limited_http_response(response: object, *, max_bytes: int) -> bytes:
    """Read a helper response without allowing an untrusted peer to exhaust RAM."""

    if max_bytes <= 0:
        raise LoginError("响应大小限制必须为正数")
    getheader = getattr(response, "getheader", None)
    if callable(getheader):
        try:
            declared = getheader("Content-Length")
            declared_length = int(declared) if declared is not None else None
        except (TypeError, ValueError):
            declared_length = None
        if declared_length is not None and (declared_length < 0 or declared_length > max_bytes):
            raise LoginError("适配器响应过大")
    reader = getattr(response, "read", None)
    if not callable(reader):
        raise LoginError("适配器响应无效")
    try:
        body = reader(max_bytes + 1)
    except TypeError:
        # Small test doubles and older wrappers may expose read() without a
        # size argument; real HTTPResponse objects take the bounded path.
        body = reader()
    if not isinstance(body, bytes) or len(body) > max_bytes:
        raise LoginError("适配器响应过大")
    return body


def push_credentials_over_https(
    credentials: WpsCredentials,
    *,
    cookies: Sequence[Mapping[str, object]],
    workspace: WpsWorkspaceSelection | None = None,
    adapter_url: str,
    username: str,
    password: str,
    timeout: float = 30.0,
    allow_insecure_http: bool = False,
    connection_factory: Callable[[str, int | None, float], object] | None = None,
) -> None:
    """Send a selected WPS cookie snapshot to the authenticated adapter.

    The adapter URL is never redirected. Remote HTTP is available only when
    explicitly enabled by the caller. The password is used only to construct
    the in-memory Basic Auth header.
    """

    scheme, host, port = _adapter_url_parts(
        adapter_url,
        allow_insecure_http=allow_insecure_http,
    )
    _validate_adapter_auth(username, password)
    if timeout <= 0:
        raise LoginError("适配器同步超时时间必须为正数")
    if not credentials.cookie or not credentials.csrf_token:
        raise LoginError("WPS 登录凭据不完整")
    payload_data: dict[str, object] = {"cookies": _cookie_payload(cookies)}
    if workspace is not None:
        payload_data["workspace"] = _workspace_payload(workspace)
    body = json.dumps(payload_data, ensure_ascii=True, separators=(",", ":")).encode("utf-8")
    authorization = base64.b64encode(f"{username}:{password}".encode("utf-8")).decode("ascii")
    if connection_factory is None:
        connection_factory = (
            HTTPSConnection if scheme == "https" else HTTPConnection
        )
    try:
        connection = connection_factory(host, port, timeout)
    except (OSError, TypeError) as exc:
        raise LoginError("无法连接适配器") from exc
    response_status: int | None = None
    try:
        try:
            connection.request(  # type: ignore[attr-defined]
                "POST",
                "/api/v1/session/import",
                body=body,
                headers={
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                    "Authorization": f"Basic {authorization}",
                    "Connection": "close",
                },
            )
            response = connection.getresponse()  # type: ignore[attr-defined]
            response_status = getattr(response, "status", None)
            _read_limited_http_response(response, max_bytes=MAX_ADAPTER_RESPONSE_BYTES)
        except (OSError, TimeoutError) as exc:
            raise LoginError("适配器同步凭据失败，请检查地址和网络") from exc
    finally:
        try:
            connection.close()  # type: ignore[attr-defined]
        except OSError:
            pass

    if response_status == 401:
        raise LoginError("适配器认证失败，请检查适配器账号和密码")
    if response_status == 404:
        raise LoginError("适配器没有凭据导入接口，请先更新 VPS 上的适配器")
    if not isinstance(response_status, int) or not 200 <= response_status < 300:
        raise LoginError(f"适配器拒绝了凭据同步（HTTP {response_status or 'unknown'}）")


class _WebSocket:
    """Tiny client for the local CDP WebSocket, using only the stdlib."""

    def __init__(self, url: str, *, timeout: float = 10.0) -> None:
        parts = urlsplit(url)
        if (
            parts.scheme != "ws"
            or not parts.hostname
            or parts.username
            or parts.password
            or not _is_loopback_host(parts.hostname)
        ):
            raise LoginError("Chrome 调试接口地址无效")
        self._socket = socket.create_connection(
            (parts.hostname, parts.port or 80),
            timeout=timeout,
        )
        self._socket.settimeout(timeout)
        self._buffer = b""
        self._closed = False
        key = base64.b64encode(secrets.token_bytes(16)).decode("ascii")
        path = parts.path or "/"
        if parts.query:
            path += "?" + parts.query
        host = parts.hostname
        if parts.port:
            host += ":" + str(parts.port)
        request = (
            f"GET {path} HTTP/1.1\r\n"
            f"Host: {host}\r\n"
            "Upgrade: websocket\r\n"
            "Connection: Upgrade\r\n"
            f"Sec-WebSocket-Key: {key}\r\n"
            "Sec-WebSocket-Version: 13\r\n"
            f"Origin: http://127.0.0.1:{parts.port or 80}\r\n"
            "\r\n"
        ).encode("ascii")
        self._socket.sendall(request)
        header = self._read_until(b"\r\n\r\n", limit=64 * 1024)
        status_line = header.split(b"\r\n", 1)[0]
        if not status_line.startswith(b"HTTP/1.1 101"):
            self.close()
            raise LoginError("无法连接 Chrome 登录会话")

    def _read_until(self, marker: bytes, *, limit: int) -> bytes:
        while marker not in self._buffer:
            chunk = self._socket.recv(4096)
            if not chunk:
                raise LoginError("Chrome 调试连接提前关闭")
            self._buffer += chunk
            if len(self._buffer) > limit:
                raise LoginError("Chrome 调试响应过大")
        index = self._buffer.index(marker) + len(marker)
        result, self._buffer = self._buffer[:index], self._buffer[index:]
        return result

    def _read_exact(self, size: int) -> bytes:
        while len(self._buffer) < size:
            chunk = self._socket.recv(max(4096, size - len(self._buffer)))
            if not chunk:
                raise LoginError("Chrome 调试连接提前关闭")
            self._buffer += chunk
        result, self._buffer = self._buffer[:size], self._buffer[size:]
        return result

    def _send_frame(self, opcode: int, payload: bytes) -> None:
        if self._closed:
            raise LoginError("Chrome 调试连接已关闭")
        length = len(payload)
        if length < 126:
            header = bytes([0x80 | opcode, 0x80 | length])
        elif length <= 0xFFFF:
            header = bytes([0x80 | opcode, 0x80 | 126]) + length.to_bytes(2, "big")
        else:
            header = bytes([0x80 | opcode, 0x80 | 127]) + length.to_bytes(8, "big")
        mask = secrets.token_bytes(4)
        masked = bytes(value ^ mask[index % 4] for index, value in enumerate(payload))
        self._socket.sendall(header + mask + masked)

    def _receive_frame(self) -> tuple[bool, int, bytes]:
        first, second = self._read_exact(2)
        final = bool(first & 0x80)
        opcode = first & 0x0F
        masked = bool(second & 0x80)
        length = second & 0x7F
        if length == 126:
            length = int.from_bytes(self._read_exact(2), "big")
        elif length == 127:
            length = int.from_bytes(self._read_exact(8), "big")
        if length > 64 * 1024 * 1024:
            raise LoginError("Chrome 调试消息过大")
        mask = self._read_exact(4) if masked else b""
        payload = self._read_exact(length)
        if mask:
            payload = bytes(value ^ mask[index % 4] for index, value in enumerate(payload))
        return final, opcode, payload

    def send_json(self, payload: Mapping[str, object]) -> None:
        self._send_frame(
            0x1,
            json.dumps(payload, ensure_ascii=True, separators=(",", ":")).encode("utf-8"),
        )

    def receive_json(self) -> Mapping[str, object]:
        message = bytearray()
        message_opcode: int | None = None
        while True:
            final, opcode, payload = self._receive_frame()
            if opcode == 0x8:
                self.close()
                raise LoginError("Chrome 调试连接已关闭")
            if opcode == 0x9:
                self._send_frame(0xA, payload)
                continue
            if opcode == 0xA:
                continue
            if opcode in {0x1, 0x2}:
                message_opcode = opcode
                message = bytearray(payload)
            elif opcode == 0x0 and message_opcode is not None:
                message.extend(payload)
            else:
                continue
            if len(message) > 64 * 1024 * 1024:
                raise LoginError("Chrome 调试消息过大")
            if final:
                if message_opcode != 0x1:
                    raise LoginError("Chrome 调试消息格式无效")
                try:
                    decoded = json.loads(bytes(message).decode("utf-8"))
                except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                    raise LoginError("Chrome 调试消息格式无效") from exc
                if not isinstance(decoded, Mapping):
                    raise LoginError("Chrome 调试消息格式无效")
                return decoded

    def call(self, method: str, params: Mapping[str, object] | None = None) -> Mapping[str, object]:
        command_id = secrets.randbelow(2**31 - 1) + 1
        payload: dict[str, object] = {"id": command_id, "method": method}
        if params:
            payload["params"] = dict(params)
        self.send_json(payload)
        while True:
            response = self.receive_json()
            if response.get("id") != command_id:
                continue
            if "error" in response:
                raise LoginError(f"Chrome 调试命令失败: {method}")
            result = response.get("result")
            if not isinstance(result, Mapping):
                raise LoginError(f"Chrome 调试命令返回无效结果: {method}")
            return result

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        try:
            self._socket.close()
        except OSError:
            pass


def _find_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.bind(("127.0.0.1", 0))
        return int(listener.getsockname()[1])


def find_browser(explicit: str | None = None) -> str:
    """Find a locally installed Chrome/Chromium executable."""

    if explicit:
        return explicit
    configured = os.environ.get("WPS_BROWSER", "").strip()
    if configured:
        return configured
    candidates = [
        "google-chrome-stable",
        "google-chrome",
        "chromium",
        "chromium-browser",
        "chrome",
    ]
    if sys.platform == "darwin":
        candidates.append("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")
    elif sys.platform == "win32":
        local_app_data = os.environ.get("LOCALAPPDATA", "")
        program_files = os.environ.get("PROGRAMFILES", "")
        candidates.extend(
            str(Path(path) / "Google/Chrome/Application/chrome.exe")
            for path in (local_app_data, program_files)
            if path
        )
    for candidate in candidates:
        path = shutil.which(candidate) or candidate
        if Path(path).is_file() and os.access(path, os.X_OK):
            return path
    raise LoginError(
        "本机没有找到 Chrome/Chromium；请安装并从自己的电脑运行此登录助手"
    )


def _cdp_page_url(port: int, *, timeout: float) -> str:
    # The endpoint is local; do not let an HTTP proxy intercept it.
    opener = build_opener(ProxyHandler({}))
    deadline = time.monotonic() + timeout
    last_error: Exception | None = None
    while time.monotonic() < deadline:
        try:
            request = Request(f"http://127.0.0.1:{port}/json/list")
            with opener.open(request, timeout=min(2.0, max(0.1, deadline - time.monotonic()))) as response:
                payload = json.loads(
                    _read_limited_http_response(
                        response,
                        max_bytes=MAX_ADAPTER_RESPONSE_BYTES,
                    ).decode("utf-8")
                )
            if isinstance(payload, list):
                for target in payload:
                    if (
                        isinstance(target, Mapping)
                        and target.get("type") == "page"
                        and isinstance(target.get("webSocketDebuggerUrl"), str)
                    ):
                        return str(target["webSocketDebuggerUrl"])
        except (OSError, URLError, TimeoutError, ValueError, json.JSONDecodeError) as exc:
            last_error = exc
        time.sleep(0.2)
    suffix = "" if last_error is None else "，请确认 Chrome 已正常启动"
    raise LoginError("等待 Chrome 登录窗口超时" + suffix)


@dataclass
class ChromeLoginSession:
    """A temporary visible Chrome profile controlled through local CDP."""

    login_url: str = DEFAULT_LOGIN_URL
    browser: str | None = None
    startup_timeout: float = 20.0
    _process: subprocess.Popen[bytes] | None = None
    _profile: tempfile.TemporaryDirectory[str] | None = None
    _connection: _WebSocket | None = None

    def __enter__(self) -> "ChromeLoginSession":
        _host_from_url(self.login_url)
        if self.startup_timeout <= 0:
            raise LoginError("Chrome 启动超时时间必须为正数")
        browser = find_browser(self.browser)
        # Chrome can keep cache files briefly after its process exits. Python
        # 3.11+ can safely ignore that cleanup race without failing login.
        self._profile = tempfile.TemporaryDirectory(
            prefix="wps-login-",
            ignore_cleanup_errors=True,
        )
        port = _find_free_port()
        command = [
            browser,
            f"--user-data-dir={self._profile.name}",
            "--no-first-run",
            "--no-default-browser-check",
            "--disable-sync",
            "--remote-debugging-address=127.0.0.1",
            f"--remote-allow-origins=http://127.0.0.1:{port}",
            f"--remote-debugging-port={port}",
            self.login_url,
        ]
        try:
            self._process = subprocess.Popen(
                command,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            page_url = _cdp_page_url(port, timeout=self.startup_timeout)
            self._connection = _WebSocket(page_url, timeout=10.0)
            return self
        except Exception:
            self.close()
            raise

    def cookies(self) -> list[Mapping[str, object]]:
        if self._connection is None:
            raise LoginError("Chrome 登录会话未启动")
        result = self._connection.call("Network.getAllCookies")
        cookies = result.get("cookies")
        if not isinstance(cookies, list):
            raise LoginError("Chrome 没有返回 Cookie")
        return [item for item in cookies if isinstance(item, Mapping)]

    def current_url(self) -> str:
        """Read the visible page URL from the isolated official WPS tab."""

        if self._connection is None:
            raise LoginError("Chrome 登录会话未启动")
        result = self._connection.call(
            "Runtime.evaluate",
            {
                "expression": "location.href",
                "returnByValue": True,
                "awaitPromise": False,
            },
        )
        value = result.get("result")
        if not isinstance(value, Mapping) or not isinstance(value.get("value"), str):
            raise LoginError("Chrome 没有返回当前页面地址")
        return value["value"]

    def navigate(self, url: str) -> None:
        """Navigate the isolated tab to an official WPS URL."""

        _host_from_url(url)
        if self._connection is None:
            raise LoginError("Chrome 登录会话未启动")
        self._connection.call("Page.navigate", {"url": url})

    def close(self) -> None:
        if self._connection is not None:
            self._connection.close()
            self._connection = None
        process = self._process
        self._process = None
        if process is not None:
            try:
                process.terminate()
                process.wait(timeout=5)
            except (OSError, subprocess.TimeoutExpired):
                try:
                    process.kill()
                except OSError:
                    pass
        profile = self._profile
        self._profile = None
        if profile is not None:
            try:
                profile.cleanup()
            except OSError:
                # A Chrome cache child can still hold a file briefly. The
                # profile is isolated and disposable, so cleanup must not
                # turn a successful credential sync into a login failure.
                pass

    def __exit__(self, _exc_type: object, _exc_value: object, _traceback: object) -> None:
        self.close()


def wait_for_login_credentials(
    session: ChromeLoginSession,
    *,
    login_url: str,
    domain_suffix: str,
    timeout: float,
) -> tuple[WpsCredentials, tuple[str, ...], list[Mapping[str, object]]]:
    """Poll the isolated browser until the WPS refresh session is available."""

    if timeout <= 0:
        raise LoginError("登录等待时间必须为正数")
    deadline = time.monotonic() + timeout
    last_error: LoginError | None = None
    while True:
        try:
            all_cookies = session.cookies()
            selected = _select_cookies(
                all_cookies,
                host=_host_from_url(login_url),
                domain_suffix=domain_suffix,
            )
            credentials, names = credentials_from_cookies(
                selected,
                base_url=login_url,
                domain_suffix=domain_suffix,
            )
            return credentials, names, selected
        except LoginError as exc:
            last_error = exc
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            detail = "请确认已在官方 WPS 页面完成登录，并且账号允许自动续期"
            if last_error is not None and "没有 rtk" in str(last_error):
                detail = "登录成功但没有找到 rtk，请确认已进入云盘页面后重试"
            raise LoginError("等待 WPS 登录完成超时；" + detail) from last_error
        time.sleep(min(0.5, remaining))


def wait_for_login_snapshot(
    session: ChromeLoginSession,
    *,
    login_url: str,
    domain_suffix: str,
    timeout: float,
    workspace_url: str | None = None,
) -> tuple[
    WpsCredentials,
    tuple[str, ...],
    list[Mapping[str, object]],
    WpsWorkspaceSelection,
]:
    """Wait for credentials and either the WPS root or an explicit folder."""

    if timeout <= 0:
        raise LoginError("登录等待时间必须为正数")
    login_host = _host_from_url(login_url)
    expected_workspace: WpsWorkspaceSelection | None = None
    if workspace_url is not None:
        if _host_from_url(workspace_url) != login_host:
            raise LoginError("--workspace-url 必须与登录地址使用同一个 WPS 主机")
        expected_workspace = workspace_from_page_url(workspace_url)
        if expected_workspace is None:
            raise LoginError(
                "--workspace-url 必须是具体文件夹地址：/space/<企业ID>/<群组ID>/<文件夹ID>"
            )
    deadline = time.monotonic() + timeout
    last_error: LoginError | None = None
    while True:
        try:
            current_url = session.current_url()
            workspace = (
                workspace_from_page_url(current_url)
                if expected_workspace is not None
                else workspace_root_from_page_url(current_url)
            )
            if workspace is None:
                if expected_workspace is not None:
                    raise LoginError("请在临时 WPS 窗口打开 --workspace-url 指定的文件夹")
                raise LoginError("请等待临时 WPS 窗口进入企业云盘；默认会使用企业云盘根目录")
            if expected_workspace is not None and workspace != expected_workspace:
                raise LoginError("当前 WPS 页面不是 --workspace-url 指定的文件夹")
            all_cookies = session.cookies()
            selected = _select_cookies(
                all_cookies,
                host=_host_from_url(login_url),
                domain_suffix=domain_suffix,
            )
            credentials, names = credentials_from_cookies(
                selected,
                base_url=login_url,
                domain_suffix=domain_suffix,
            )
            return credentials, names, selected, workspace
        except LoginError as exc:
            last_error = exc
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            detail = (
                "请完成 WPS 登录，并在同一窗口打开 --workspace-url 指定的文件夹"
                if expected_workspace is not None
                else "请完成 WPS 登录并进入企业云盘；默认目标是企业云盘根目录"
            )
            if last_error is not None and "没有 rtk" in str(last_error):
                detail = "登录成功但没有找到 rtk，请确认已进入云盘页面后重试"
            raise LoginError("等待 WPS 登录和工作区选择超时；" + detail) from last_error
        time.sleep(min(0.5, remaining))


def _workspace_candidate_value(item: Mapping[str, object], keys: Sequence[str]) -> object:
    for key in keys:
        if key in item:
            return item[key]
    return None


def discover_workspaces(
    credentials: WpsCredentials,
    *,
    tenant_id: str,
    base_url: str = DEFAULT_LOGIN_URL,
    timeout: float = 30.0,
    opener: object | None = None,
) -> tuple[WpsWorkspaceCandidate, ...]:
    """Discover spaces visible to the logged-in account.

    The path is the OpenList-compatible enterprise endpoint.  Its response
    is treated as untrusted: only a group ID and a display name are retained.
    Callers must still verify the selected group through the observed file
    listing endpoint before persisting it.
    """

    if not isinstance(credentials, WpsCredentials) or not credentials.cookie:
        raise LoginError("WPS 登录凭据不完整，无法发现工作区")
    tenant_id = _workspace_id(tenant_id, field_name="企业 ID")
    if timeout <= 0:
        raise LoginError("工作区发现超时时间必须为正数")
    host = _host_from_url(base_url)
    url = urlunsplit(
        (
            "https",
            host,
            f"/3rd/plus/groups/v1/companies/{quote(tenant_id, safe='')}/users/self/groups/private",
            "",
            "",
        )
    )
    request = Request(
        url,
        headers={
            "Accept": "application/json",
            "Cookie": credentials.cookie,
            "User-Agent": "wps-adapter-login/1",
        },
        method="GET",
    )
    client = opener or build_opener(ProxyHandler({}))
    try:
        response = client.open(request, timeout=timeout)  # type: ignore[attr-defined]
        try:
            body = _read_limited_http_response(response, max_bytes=MAX_ADAPTER_RESPONSE_BYTES)
        finally:
            close = getattr(response, "close", None)
            if callable(close):
                close()
    except HTTPError as exc:
        try:
            exc.close()
        except OSError:
            pass
        raise LoginError(f"WPS 企业空间发现失败（HTTP {exc.code}）") from exc
    except (OSError, URLError, TimeoutError, ValueError) as exc:
        raise LoginError("无法连接 WPS 企业空间发现接口") from exc
    try:
        payload = json.loads(body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise LoginError("WPS 企业空间发现返回了无效响应") from exc

    raw_items: object = payload
    if isinstance(payload, dict):
        for key in ("groups", "spaces", "data", "list"):
            if isinstance(payload.get(key), list):
                raw_items = payload[key]
                break
    if not isinstance(raw_items, list):
        raise LoginError("WPS 企业空间发现返回格式异常")
    candidates: list[WpsWorkspaceCandidate] = []
    seen: set[str] = set()
    for raw_item in raw_items:
        if not isinstance(raw_item, Mapping):
            continue
        raw_group_id = _workspace_candidate_value(raw_item, ("group_id", "groupid", "id"))
        raw_name = _workspace_candidate_value(raw_item, ("name", "group_name", "groupname", "title"))
        if isinstance(raw_group_id, bool) or raw_group_id is None:
            continue
        group_id = str(raw_group_id)
        name = str(raw_name).strip() if raw_name is not None else ""
        try:
            group_id = _workspace_id(group_id, field_name="群组 ID")
        except LoginError:
            continue
        if not name or len(name) > 256 or any(ord(char) < 0x20 or ord(char) == 0x7F for char in name):
            continue
        if group_id in seen:
            continue
        seen.add(group_id)
        candidates.append(WpsWorkspaceCandidate(tenant_id, group_id, name))
    return tuple(candidates)


def verify_workspace_access(
    credentials: WpsCredentials,
    workspace: WpsWorkspaceSelection,
    *,
    base_url: str = DEFAULT_LOGIN_URL,
    timeout: float = 30.0,
    opener: object | None = None,
) -> None:
    """Verify the selected WPS workspace before persisting new credentials.

    This uses the already observed enterprise file-list endpoint only. It is
    deliberately separate from OpenList's unverified group-discovery
    candidate: a page-derived or explicitly selected workspace must first
    prove that its root is readable with the newly captured session.
    """

    if not isinstance(credentials, WpsCredentials) or not credentials.cookie:
        raise LoginError("WPS 登录凭据不完整，无法验证工作区")
    if not isinstance(workspace, WpsWorkspaceSelection):
        raise LoginError("WPS 工作区信息无效，无法验证访问权限")
    if timeout <= 0:
        raise LoginError("工作区验证超时时间必须为正数")
    host = _host_from_url(base_url)
    group_id = _workspace_id(workspace.group_id, field_name="群组 ID")
    root_id = _workspace_id(workspace.root_id, field_name="目录 ID")
    query = urlencode(
        {
            "parentid": root_id,
            "offset": "0",
            "count": "1",
            "orderby": "mtime",
            "order": "desc",
        }
    )
    url = urlunsplit(
        (
            "https",
            host,
            f"/3rd/drive/api/v5/groups/{quote(group_id, safe='')}/files",
            query,
            "",
        )
    )
    request = Request(
        url,
        headers={
            "Accept": "application/json",
            "Cookie": credentials.cookie,
            "User-Agent": "wps-adapter-login/1",
        },
        method="GET",
    )
    client = opener or build_opener(ProxyHandler({}))
    try:
        response = client.open(request, timeout=timeout)  # type: ignore[attr-defined]
        try:
            body = _read_limited_http_response(response, max_bytes=MAX_ADAPTER_RESPONSE_BYTES)
        finally:
            close = getattr(response, "close", None)
            if callable(close):
                close()
    except HTTPError as exc:
        try:
            exc.close()
        except OSError:
            pass
        if exc.code == 401:
            raise LoginError("WPS 登录已过期，未同步新凭据") from exc
        if exc.code in {403, 404}:
            raise LoginError("当前账号无权访问所选 WPS 工作区，未同步新凭据") from exc
        raise LoginError(f"WPS 工作区验证失败（HTTP {exc.code}），未同步新凭据") from exc
    except (OSError, URLError, TimeoutError, ValueError) as exc:
        raise LoginError("无法连接 WPS 验证工作区，未同步新凭据") from exc
    try:
        payload = json.loads(body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise LoginError("WPS 工作区验证返回了无效响应，未同步新凭据") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("files"), list):
        raise LoginError("WPS 工作区验证返回格式异常，未同步新凭据")
    if payload.get("result") not in {None, "ok"}:
        raise LoginError("WPS 工作区验证未成功，未同步新凭据")


def login_and_sync(
    *,
    login_url: str = DEFAULT_LOGIN_URL,
    browser: str | None = None,
    domain_suffix: str = DEFAULT_COOKIE_DOMAIN_SUFFIX,
    wait_timeout: float = 300.0,
    ssh_target: str = "",
    ssh_cookie_path: str = DEFAULT_REMOTE_COOKIE_PATH,
    ssh_csrf_path: str = DEFAULT_REMOTE_CSRF_PATH,
    ssh_workspace_path: str = DEFAULT_REMOTE_WORKSPACE_PATH,
    ssh_identity: str | None = None,
    ssh_port: int = 22,
    ssh_password_auth: bool = False,
    output_dir: str | None = None,
    ssh_timeout: float = 30.0,
    adapter_url: str = "",
    adapter_user: str = "",
    adapter_password: str | None = None,
    adapter_timeout: float = 30.0,
    allow_insecure_http: bool = False,
    workspace_url: str | None = None,
    workspace_selector: Callable[[Sequence[WpsWorkspaceCandidate]], object] | None = None,
) -> tuple[str, ...]:
    """Open WPS, wait for a human login, then sync a safe credential snapshot."""

    target_count = sum(bool(target) for target in (ssh_target, output_dir, adapter_url))
    if target_count != 1:
        raise LoginError("请在 --adapter-url、--ssh-target 和 --output-dir 中选择一个同步目标")
    if wait_timeout <= 0:
        raise LoginError("登录等待时间必须为正数")
    if output_dir is not None and not Path(output_dir).is_absolute():
        raise LoginError("本地凭据目录必须是绝对路径")
    browser_url = login_url
    if workspace_url is not None:
        login_host = _host_from_url(login_url)
        if _host_from_url(workspace_url) != login_host:
            raise LoginError("--workspace-url 必须与登录地址使用同一个 WPS 主机")
        if workspace_from_page_url(workspace_url) is None:
            raise LoginError(
                "--workspace-url 必须是具体文件夹地址：/space/<企业ID>/<群组ID>/<文件夹ID>"
            )
        browser_url = workspace_url
    if adapter_url:
        _adapter_url_parts(
            adapter_url,
            allow_insecure_http=allow_insecure_http,
        )
        _validate_adapter_auth(adapter_user, adapter_password or "")
        if adapter_timeout <= 0:
            raise LoginError("适配器同步超时时间必须为正数")
    discovered_workspaces: tuple[WpsWorkspaceCandidate, ...] = ()
    with ChromeLoginSession(login_url=browser_url, browser=browser) as session:
        print("WPS 登录窗口已打开。请只在这个官方 WPS 窗口中完成登录。", flush=True)
        if workspace_url is None:
            print(
                "登录后脚本会自动获取可用 WPS 空间；WPS 自动跳转到的旧文件夹不会被当作目标。",
                flush=True,
            )
        else:
            print(
                "登录后请在临时 WPS 窗口打开 --workspace-url 指定的文件夹；脚本会校验当前目录。",
                flush=True,
            )
        try:
            if workspace_url is None:
                credentials, names, selected_cookies = wait_for_login_credentials(
                    session,
                    login_url=browser_url,
                    domain_suffix=domain_suffix,
                    timeout=wait_timeout,
                )
                page_workspace = workspace_root_from_page_url(session.current_url())
                tenant_id = page_workspace.tenant_id if page_workspace is not None else _cookie_value(selected_cookies, "cid")
                if not tenant_id:
                    raise LoginError("无法识别 WPS 企业空间，请确认已登录学校云盘")
                workspace = page_workspace or WpsWorkspaceSelection(tenant_id, "", "0")
            else:
                credentials, names, selected_cookies, workspace = wait_for_login_snapshot(
                    session,
                    login_url=browser_url,
                    domain_suffix=domain_suffix,
                    timeout=wait_timeout,
                    workspace_url=workspace_url,
                )
        except KeyboardInterrupt as exc:
            raise LoginError("已取消登录同步") from exc
        print(
            f"已获取 {len(names)} 个 WPS Cookie（包含 rtk 和 csrf）；Cookie 值不会显示。",
            flush=True,
        )
        if workspace_url is None:
            try:
                discovered_workspaces = discover_workspaces(
                    credentials,
                    tenant_id=workspace.tenant_id,
                    base_url=browser_url,
                    timeout=adapter_timeout,
                )
            except LoginError as exc:
                print(f"自动发现企业空间失败：{exc}；将使用当前页面中的空间。", flush=True)
            if not discovered_workspaces:
                if not workspace.group_id:
                    print("没有发现可选企业空间；将使用当前页面中的空间。", flush=True)
    if workspace_url is None and discovered_workspaces:
        selected = discovered_workspaces[0] if workspace_selector is None else workspace_selector(discovered_workspaces)
        if isinstance(selected, WpsWorkspaceCandidate):
            selected_candidates = (selected,)
        elif isinstance(selected, Sequence) and not isinstance(selected, (str, bytes)):
            selected_candidates = tuple(selected)
        else:
            raise LoginError("未选择有效的 WPS 工作区，未同步新凭据")
        if not selected_candidates or any(not isinstance(item, WpsWorkspaceCandidate) for item in selected_candidates):
            raise LoginError("未选择有效的 WPS 工作区，未同步新凭据")
        selected_candidate = selected_candidates[0]
        workspace = WpsWorkspaceSelection(
            tenant_id=selected_candidate.tenant_id,
            group_id=selected_candidate.group_id,
            root_id="0",
            spaces=tuple(selected_candidates),
        )
    print("正在验证 WPS 工作区访问权限...", flush=True)
    if workspace.spaces:
        for candidate in workspace.spaces:
            verify_workspace_access(
                credentials,
                WpsWorkspaceSelection(candidate.tenant_id, candidate.group_id, "0"),
                base_url=browser_url,
                timeout=adapter_timeout,
            )
    else:
        verify_workspace_access(credentials, workspace, base_url=browser_url, timeout=adapter_timeout)
    print("工作区验证成功，准备同步凭据。", flush=True)
    if ssh_target:
        push_credentials_over_ssh(
            credentials,
            ssh_target=ssh_target,
            cookie_path=ssh_cookie_path,
            csrf_path=ssh_csrf_path,
            workspace=workspace,
            workspace_path=ssh_workspace_path,
            identity_file=ssh_identity,
            port=ssh_port,
            password_auth=ssh_password_auth,
            timeout=ssh_timeout,
        )
        print("已通过 SSH 更新 VPS 凭据，适配器下次请求会读取新会话。", flush=True)
    elif adapter_url:
        push_credentials_over_https(
            credentials,
            cookies=selected_cookies,
            workspace=workspace,
            adapter_url=adapter_url,
            username=adapter_user,
            password=adapter_password or "",
            timeout=adapter_timeout,
            allow_insecure_http=allow_insecure_http,
        )
        scheme = urlsplit(adapter_url).scheme.upper()
        print(f"已通过 {scheme} 更新适配器凭据，服务无需重启。", flush=True)
    else:
        cookie_path, csrf_path = write_local_credentials(credentials, output_dir=output_dir or "")
        workspace_path = write_local_workspace(workspace, output_dir=output_dir or "")
        print(f"已写入本地凭据文件：{cookie_path}、{csrf_path}；工作区信息：{workspace_path}", flush=True)
    return names


"""Command-line interface shared by the package and standalone login helper."""

import argparse
import getpass
import os
import sys
from dataclasses import dataclass
from urllib.parse import urlsplit, urlunsplit

def _env_int(name: str, default: int) -> int:
    value = os.environ.get(name)
    return default if value is None else int(value)


def add_login_arguments(parser: argparse.ArgumentParser) -> None:
    """Add login-helper arguments to a parser."""

    parser.add_argument("--login-url", default=DEFAULT_LOGIN_URL)
    parser.add_argument(
        "--workspace-url",
        default=None,
        help="指定具体 WPS 文件夹 URL；省略时使用企业云盘根目录",
    )
    parser.add_argument("--browser", default=None, help="local Chrome/Chromium executable")
    parser.add_argument("--domain-suffix", default=DEFAULT_COOKIE_DOMAIN_SUFFIX)
    parser.add_argument("--wait-timeout", type=float, default=300.0)
    parser.add_argument(
        "--adapter-url",
        default=os.environ.get("WPS_ADAPTER_URL", ""),
        help="HTTP or HTTPS adapter origin for direct credential sync",
    )
    parser.add_argument(
        "--adapter-user",
        default=os.environ.get("WPS_ADAPTER_USER", ""),
        help="adapter Basic Auth username; the password is prompted securely",
    )
    parser.add_argument(
        "--adapter-port",
        type=int,
        default=None,
        help="adapter port; use with --adapter-url when it has no port",
    )
    parser.add_argument(
        "--allow-http",
        action="store_true",
        help="allow sending the WPS session to a remote adapter over HTTP",
    )
    parser.add_argument("--adapter-timeout", type=float, default=30.0)
    parser.add_argument(
        "--ssh-target",
        default=os.environ.get("WPS_ADAPTER_SSH_TARGET", ""),
        help="remote SSH target, for example root@203.0.113.10",
    )
    parser.add_argument("--ssh-identity", default=None)
    parser.add_argument("--ssh-port", type=int, default=_env_int("WPS_ADAPTER_SSH_PORT", 22))
    parser.add_argument(
        "--ssh-password-auth",
        action="store_true",
        help="force password/keyboard-interactive SSH authentication",
    )
    parser.add_argument("--ssh-cookie-path", default=DEFAULT_REMOTE_COOKIE_PATH)
    parser.add_argument("--ssh-csrf-path", default=DEFAULT_REMOTE_CSRF_PATH)
    parser.add_argument("--ssh-workspace-path", default=DEFAULT_REMOTE_WORKSPACE_PATH)
    parser.add_argument("--ssh-timeout", type=float, default=30.0)
    parser.add_argument(
        "--output-dir",
        default=None,
        help="write credentials and wps-workspace.json to this local absolute directory",
    )


@dataclass(frozen=True, slots=True)
class _LoginTarget:
    adapter_url: str = ""
    adapter_port: int | None = None
    adapter_user: str = ""
    ssh_target: str = ""
    ssh_identity: str | None = None
    ssh_port: int = 22
    ssh_password_auth: bool = False


def _prompt_port(label: str, default: int) -> int:
    while True:
        value = input(f"{label} [{default}]: ").strip() or str(default)
        try:
            port = int(value)
        except ValueError:
            print("端口必须是数字，请重新输入。")
            continue
        if 1 <= port <= 65535:
            return port
        print("端口必须在 1 到 65535 之间，请重新输入。")


def _prompt_login_target() -> _LoginTarget:
    print("提示：[] 里面的是默认选项，直接按回车即可使用。")
    host = input("VPS 地址/IP或域名: ").strip()
    if not host or any(char.isspace() for char in host):
        raise LoginError("VPS 地址不能为空且不能包含空格")
    print("选择连接方式：")
    print("  1) SSH 私钥")
    print("  2) SSH 密码")
    print("  3) HTTP/HTTPS 适配器接口")
    while True:
        choice = input("连接方式 [1]: ").strip() or "1"
        if choice in {"1", "2", "3"}:
            break
        print("请输入 1、2 或 3。")

    if choice in {"1", "2"}:
        user = input("SSH 用户名 [root]: ").strip() or "root"
        if not user or any(char.isspace() or char in "@/\\" for char in user):
            raise LoginError("SSH 用户名格式不正确")
        port = _prompt_port("SSH 端口", 22)
        if choice == "2":
            print("WPS 登录完成后，系统 ssh 会在传输凭据时询问 SSH 密码。")
            return _LoginTarget(
                ssh_target=f"{user}@{host}",
                ssh_port=port,
                ssh_password_auth=True,
            )
        identity = input("SSH 私钥路径 [~/.ssh/id_ed25519]: ").strip()
        identity = identity or "~/.ssh/id_ed25519"
        return _LoginTarget(
            ssh_target=f"{user}@{host}",
            ssh_identity=os.path.expanduser(identity),
            ssh_port=port,
        )

    host_for_url = host
    if ":" in host and not host.startswith("["):
        host_for_url = f"[{host}]"
    adapter_port = _prompt_port("适配器端口", 54321)
    default_url = f"http://{host_for_url}:{adapter_port}"
    entered_url = input(f"适配器 HTTP/HTTPS 地址 [{default_url}]: ").strip()
    adapter_url = entered_url or default_url
    try:
        explicit_port = urlsplit(adapter_url).port
    except ValueError:
        explicit_port = None
    if entered_url and explicit_port is not None and explicit_port != adapter_port:
        raise LoginError("适配器地址中的端口与端口输入不一致")
    return _LoginTarget(
        adapter_url=adapter_url,
        adapter_port=adapter_port,
    )


def _apply_adapter_port(adapter_url: str, port: int | None) -> str:
    if port is None:
        return adapter_url
    if not 1 <= port <= 65535:
        raise LoginError("适配器端口必须在 1 到 65535 之间")
    parts = urlsplit(adapter_url)
    try:
        existing_port = parts.port
    except ValueError as exc:
        raise LoginError("适配器地址中的端口无效") from exc
    if existing_port is not None and existing_port != port:
        raise LoginError("适配器地址中的端口与 --adapter-port 不一致")
    if existing_port is not None:
        return adapter_url
    if not parts.hostname:
        raise LoginError("适配器地址缺少主机名")
    hostname = parts.hostname
    netloc = f"[{hostname}]" if ":" in hostname else hostname
    return urlunsplit((parts.scheme, f"{netloc}:{port}", parts.path, parts.query, parts.fragment))


def _select_workspace(candidates: tuple[WpsWorkspaceCandidate, ...]) -> WpsWorkspaceCandidate:
    """Let a normal user choose a space by its name, never by its ID."""

    if len(candidates) == 1:
        print(f"已找到 WPS 空间：{candidates[0].name}，将自动使用它。", flush=True)
        return candidates[0]
    print(f"发现 {len(candidates)} 个可用 WPS 空间：", flush=True)
    for index, candidate in enumerate(candidates, 1):
        print(f"  [{index}] {candidate.name}", flush=True)
    while True:
        answer = input("请选择空间 [1]: ").strip() or "1"
        try:
            index = int(answer)
        except ValueError:
            print("请输入列表中的序号。", flush=True)
            continue
        if 1 <= index <= len(candidates):
            return candidates[index - 1]
        print("请输入列表中的序号。", flush=True)


def _select_workspaces(candidates: tuple[WpsWorkspaceCandidate, ...]) -> tuple[WpsWorkspaceCandidate, ...]:
    """Select one, several, or all discovered spaces by display name."""

    if len(candidates) == 1:
        print(f"已找到 WPS 空间：{candidates[0].name}，将自动使用它。", flush=True)
        return candidates
    print(f"发现 {len(candidates)} 个可用 WPS 空间：", flush=True)
    for index, candidate in enumerate(candidates, 1):
        print(f"  [{index}] {candidate.name}", flush=True)
    print("可输入一个或多个序号（例如 1,3），也可以输入 all 使用全部空间。", flush=True)
    while True:
        answer = input("请选择空间 [1]: ").strip() or "1"
        if answer.casefold() == "all":
            return candidates
        try:
            indexes = [int(value.strip()) for value in answer.split(",")]
        except ValueError:
            print("请输入序号，例如 1,3，或输入 all。", flush=True)
            continue
        if not indexes or len(set(indexes)) != len(indexes) or any(
            index < 1 or index > len(candidates) for index in indexes
        ):
            print("请输入列表中的序号。", flush=True)
            continue
        return tuple(candidates[index - 1] for index in indexes)


def run_login(args: argparse.Namespace, *, interactive: bool = True) -> int:
    """Run the login flow and return a process exit code."""

    interactive_target = (
        _prompt_login_target()
        if interactive and not args.adapter_url and not args.ssh_target and args.output_dir is None
        else _LoginTarget(
            adapter_url=args.adapter_url,
            adapter_port=args.adapter_port,
            adapter_user=args.adapter_user,
            ssh_target=args.ssh_target,
            ssh_identity=args.ssh_identity,
            ssh_port=args.ssh_port,
            ssh_password_auth=args.ssh_password_auth,
        )
    )
    adapter_url = (
        _apply_adapter_port(
            interactive_target.adapter_url,
            interactive_target.adapter_port,
        )
        if interactive_target.adapter_url
        else ""
    )
    allow_insecure_http = args.allow_http
    if adapter_url and is_remote_http_url(adapter_url):
        print(
            "警告：HTTP 不加密，WPS Cookie、Basic Auth 和文件请求可能被窃听。",
            flush=True,
        )
        if not allow_insecure_http:
            confirmation = input("仍然通过 HTTP 发送 Cookie？ [y/N]: ").strip().casefold()
            if confirmation not in {"y", "yes"}:
                raise LoginError("已取消明文 HTTP 凭据同步；如确认风险可使用 --allow-http")
            allow_insecure_http = True
    adapter_user = interactive_target.adapter_user
    adapter_password: str | None = None
    if adapter_url:
        if not adapter_user:
            adapter_user = input("适配器用户名: ").strip()
        adapter_password = getpass.getpass("适配器密码（不会显示）: ")
    login_and_sync(
        login_url=args.login_url,
        workspace_url=args.workspace_url,
        browser=args.browser,
        domain_suffix=args.domain_suffix,
        wait_timeout=args.wait_timeout,
        ssh_target=interactive_target.ssh_target,
        ssh_cookie_path=args.ssh_cookie_path,
        ssh_csrf_path=args.ssh_csrf_path,
        ssh_workspace_path=args.ssh_workspace_path,
        ssh_identity=interactive_target.ssh_identity,
        ssh_port=interactive_target.ssh_port,
        ssh_password_auth=interactive_target.ssh_password_auth,
        output_dir=args.output_dir,
        ssh_timeout=args.ssh_timeout,
        adapter_url=adapter_url,
        adapter_user=adapter_user,
        adapter_password=adapter_password,
        adapter_timeout=args.adapter_timeout,
        allow_insecure_http=allow_insecure_http,
        workspace_selector=_select_workspaces if interactive and not args.workspace_url else None,
    )
    return 0


def run_login_safely(args: argparse.Namespace, *, interactive: bool = True) -> int:
    """Run the login flow with user-facing error handling."""

    try:
        return run_login(args, interactive=interactive)
    except (EOFError, KeyboardInterrupt):
        print("login failed: 已取消登录同步", file=sys.stderr)
        return 1
    except (LoginError, OSError, ValueError) as exc:
        print(f"login failed: {exc}", file=sys.stderr)
        return 1


__all__ = [
    "_apply_adapter_port",
    "_prompt_login_target",
    "add_login_arguments",
    "run_login",
    "run_login_safely",
]


__version__ = '0.9.8'


def _standalone_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="WPS enterprise cloud drive login helper (standalone)"
    )
    parser.add_argument("--version", action="version", version=__version__)
    add_login_arguments(parser)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _standalone_parser().parse_args(argv)
    return run_login_safely(args)


if __name__ == "__main__":
    raise SystemExit(main())
