#!/usr/bin/env python3
"""Build the downloadable, dependency-free WPS login helper."""

from __future__ import annotations

import re
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOGIN_SOURCE_PATH = PROJECT_ROOT / "src" / "wps_adapter" / "login.py"
COMMAND_SOURCE_PATH = PROJECT_ROOT / "src" / "wps_adapter" / "login_command.py"
OUTPUT_PATH = PROJECT_ROOT / "wps_login.py"

_CREDENTIAL_IMPORT = "from .client import WpsCredentials"
_STANDALONE_CREDENTIAL_CLASS = '''from dataclasses import field

@dataclass(frozen=True, slots=True)
class WpsCredentials:
    """A point-in-time credential snapshot for the standalone helper."""

    cookie: str = field(default="", repr=False)
    csrf_token: str = field(default="", repr=False)
'''


def _remove_command_import(source: str) -> str:
    start_marker = "from .login import ("
    start = source.index(start_marker)
    end = source.index("\n\ndef _env_int", start)
    return source[:start] + source[end + 2 :]


def _remove_future_import(source: str) -> str:
    return source.replace("from __future__ import annotations\n\n", "", 1)


def _version() -> str:
    source = (PROJECT_ROOT / "src" / "wps_adapter" / "__init__.py").read_text(
        encoding="utf-8"
    )
    match = re.search(r'^__version__\s*=\s*[\"\']([^\"\']+)[\"\']', source, re.MULTILINE)
    if match is None:
        raise RuntimeError("could not find package version")
    return match.group(1)


def build() -> str:
    login_source = LOGIN_SOURCE_PATH.read_text(encoding="utf-8")
    if login_source.count(_CREDENTIAL_IMPORT) != 1:
        raise RuntimeError("login.py credential import changed; update the builder")
    login_source = login_source.replace(_CREDENTIAL_IMPORT, _STANDALONE_CREDENTIAL_CLASS, 1)

    command_source = COMMAND_SOURCE_PATH.read_text(encoding="utf-8")
    command_source = _remove_command_import(command_source)
    command_source = _remove_future_import(command_source)

    version_literal = repr(_version())
    standalone_main = f'''

__version__ = {version_literal}


def _standalone_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="WPS enterprise cloud drive login helper (standalone)"
    )
    parser.add_argument("--version", action="version", version=__version__)
    add_login_arguments(parser)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _standalone_parser().parse_args(argv)
    return run_login_safely(args)


if __name__ == "__main__":
    raise SystemExit(main())
'''
    return (
        "#!/usr/bin/env python3\n"
        "# Generated by tools/build_login_script.py; edit the source modules instead.\n"
        + login_source
        + "\n\n"
        + command_source
        + standalone_main
    )


def main() -> int:
    generated = build()
    if "--check" in sys.argv[1:]:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != generated:
            print(f"{OUTPUT_PATH} is out of date", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    OUTPUT_PATH.chmod(0o755)
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
